### ISSUE TITLE
Story Creation Tool: CleverPush

### ISSUE THREAD

**Issue by gbhrdt** [ampproject/amp.dev#5480]
### Story creation resource name

CleverPush

### Type

Use [x] to mark a selection:

- [x] Story Creation Tool
- [ ] CMS
- [ ] Platform
- [ ] Other

### URL

https://cleverpush.com/

### Image

<img width="1455" alt="Bildschirmfoto 2021-03-06 um 13 32 29" src="https://user-images.githubusercontent.com/1145196/110206844-717f1680-7e80-11eb-998f-21a23fadd2f2.png">

### Description

Easily create, publish and analyze professional Web Stories with CleverPush.

### List of Stories

https://stories.bildderfrau.de/die-koestlichsten-fruehstucksrezepte
https://stories.bildderfrau.de/dessert-rezepte-weihnachten
https://stories.giga.de/ps5
https://stories.giga.de/prime-day
https://stories.futurezone.de/krebserregende-lebensmittel
https://stories.futurezone.de/signal-app
https://stories.desired.de/stars
https://stories.waz.de/ffp2masken
https://stories.wmn.de/kon-mari-methode-aufraeumen
https://www.rtl.de/cms/stories/das-grosse-interview-mit-harry-und-meghan/

**Comment by matthiasrohmer** [comment]
Thanks for filing this! Someone of the AMP Stories team (@shishirm, tentatively) will take care of reviewing your submitted stories. This can take a while though we hence like to ask you for a little patience.

**Comment by patrickkettner** [comment]
@sdenaro would this be something you can look at?

**Comment by sdenaro** [comment]
@patrickkettner let me see who has bandwidth and then lets assign it to them.

**Comment by sdenaro** [comment]
@patrickkettner  can you assign this to @Dbrown910

**Comment by patrickkettner** [comment]
@sdenaro I can't - I assume they aren't a part of the @ampproject group?

**Comment by Dbrown910** [comment]
@patrickkettner Nope, I'm not in the group. Let me know what I need to do to join. I'll take care of this in the mean time

@gbhrdt 
 I've done a review of the stories URLs you submitted. Here's the feedback, please let me know if there's any confusion. 

1. AMP Validation - Almost all of the stories were facing some kind of validation issues. The AMP runtime is very strict about what is allowed. You can verify your stories using the _#development=1_ param after your URLs. The debug tab will list out any validation errors. Here is [a reference](https://amp.dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors/?format=websites) for sorting out these issues.

2. storymetadatathumbnailsareok - Some piece of your Story's image metadata was off size or incorrectly formmated. Here are [the guidelines](https://amp.dev/documentation/components/amp-story/#metadata-guidelines). Ensure you meet the minimum size, aspect ratio and file type

3. ampvideoissmall - Videos need to be compressed to 4MB or less

**COMPLETE FEEDBACK**

###################################################
https://stories.bildderfrau.de/die-koestlichsten-fruehstucksrezepte
###################################################
ampimgamppixelpreferred (PASS)

ampimgheightwidthisok (PASS)

ampvideoissmall (PASS)

ampvideoisspecifiedbyattribute (PASS)

bookendexists (WARN)

  <amp-story-bookend> not found

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

runtimeispreloaded (WARN)

  <link href=https://cdn.ampproject.org/v0.js rel=preload> is missing

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"https://static.cleverpush.com/notification/icon/XQaMnrQuSgKsrBLwn.png","width":640,"height":853,"mime":"image/png"}] failed [isAtLeast696x928]

storymetadatathumbnailsareok (FAIL)

  [poster-square-src = {"url":"https://static.cleverpush.com/notification/icon/i7rq6YJdwy74BMjCh.png","width":640,"height":853,"mime":"image/png"}] failed [isSquare, isAtLeast928x928]

storyruntimeisv1 (PASS)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
###################################################
https://stories.bildderfrau.de/dessert-rezepte-weihnachten
###################################################
ampimgamppixelpreferred (PASS)

ampimgheightwidthisok (PASS)

ampvideoissmall (PASS)

ampvideoisspecifiedbyattribute (PASS)

bookendexists (WARN)

  <amp-story-bookend> not found

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

runtimeispreloaded (WARN)

  <link href=https://cdn.ampproject.org/v0.js rel=preload> is missing

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (PASS)

storyruntimeisv1 (PASS)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
###################################################
https://stories.giga.de/ps5
###################################################
ampimgamppixelpreferred (PASS)

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/d7aK3uHvj49s6gnEr.png]: actual ratio [3160/1270 = 2.48] does not match specified [101/40 = 2.52]

ampvideoissmall (PASS)

ampvideoisspecifiedbyattribute (PASS)

bookendexists (WARN)

  <amp-story-bookend> not found

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

runtimeispreloaded (WARN)

  <link href=https://cdn.ampproject.org/v0.js rel=preload> is missing

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (PASS)

storyruntimeisv1 (PASS)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
###################################################
https://stories.giga.de/prime-day
###################################################
ampimgamppixelpreferred (PASS)

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/reyibCpayvQkvivRy.png]: actual ratio [3160/1270 = 2.48] does not match specified [101/40 = 2.52]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/jf5ZfX7PrLtqP9H3S.png]: actual ratio [3160/1270 = 2.48] does not match specified [103/41 = 2.51]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/jf5ZfX7PrLtqP9H3S.png]: actual ratio [3160/1270 = 2.48] does not match specified [103/41 = 2.51]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/jf5ZfX7PrLtqP9H3S.png]: actual ratio [3160/1270 = 2.48] does not match specified [103/41 = 2.51]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/jf5ZfX7PrLtqP9H3S.png]: actual ratio [3160/1270 = 2.48] does not match specified [103/41 = 2.51]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/AGP4y5WXKsqRgavrJ.png]: actual ratio [3160/1270 = 2.48] does not match specified [101/40 = 2.52]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/jf5ZfX7PrLtqP9H3S.png]: actual ratio [3160/1270 = 2.48] does not match specified [101/40 = 2.52]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/jf5ZfX7PrLtqP9H3S.png]: actual ratio [3160/1270 = 2.48] does not match specified [101/40 = 2.52]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/jf5ZfX7PrLtqP9H3S.png]: actual ratio [3160/1270 = 2.48] does not match specified [103/41 = 2.51]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/jf5ZfX7PrLtqP9H3S.png]: actual ratio [3160/1270 = 2.48] does not match specified [103/41 = 2.51]

ampvideoissmall (PASS)

ampvideoisspecifiedbyattribute (PASS)

bookendexists (WARN)

  <amp-story-bookend> not found

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

runtimeispreloaded (WARN)

  <link href=https://cdn.ampproject.org/v0.js rel=preload> is missing

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"https://static.cleverpush.com/notification/icon/uc57ES53EWq3fkuhb.png","width":300,"height":400,"mime":"image/png"}] failed [isAtLeast696x928]

storyruntimeisv1 (PASS)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
###################################################
https://stories.futurezone.de/krebserregende-lebensmittel
###################################################
ampimgamppixelpreferred (PASS)

ampimgheightwidthisok (PASS)

ampvideoissmall (PASS)

ampvideoisspecifiedbyattribute (PASS)

bookendexists (WARN)

  <amp-story-bookend> not found

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

runtimeispreloaded (WARN)

  <link href=https://cdn.ampproject.org/v0.js rel=preload> is missing

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"https://static.cleverpush.com/notification/icon/cg5BWDw7ScJghTWMB.png","width":650,"height":853,"mime":"image/png"}] failed [isPortrait, isAtLeast696x928]

storyruntimeisv1 (PASS)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
###################################################
https://stories.futurezone.de/signal-app
###################################################
ampimgamppixelpreferred (PASS)

ampimgheightwidthisok (PASS)

ampvideoissmall (PASS)

ampvideoisspecifiedbyattribute (PASS)

bookendexists (WARN)

  <amp-story-bookend> not found

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

runtimeispreloaded (WARN)

  <link href=https://cdn.ampproject.org/v0.js rel=preload> is missing

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"https://static.cleverpush.com/notification/icon/bpv9PCM3eEoyKaYTB.png","width":650,"height":853,"mime":"image/png"}] failed [isPortrait, isAtLeast696x928]

storyruntimeisv1 (PASS)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
###################################################
https://stories.desired.de/stars
###################################################
ampimgamppixelpreferred (PASS)

ampimgheightwidthisok (PASS)

ampvideoissmall (PASS)

ampvideoisspecifiedbyattribute (PASS)

bookendexists (WARN)

  <amp-story-bookend> not found

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

runtimeispreloaded (WARN)

  <link href=https://cdn.ampproject.org/v0.js rel=preload> is missing

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (PASS)

storyruntimeisv1 (PASS)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
###################################################
https://stories.waz.de/ffp2masken
###################################################
ampimgamppixelpreferred (PASS)

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/gECy7uGSZtYMdvp8F.png]: actual ratio [1080/1920 = 0.56] does not match specified [348/581 = 0.59]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/mumvZzdKrB6B6uuGP.png]: actual ratio [1080/1920 = 0.56] does not match specified [348/581 = 0.59]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/qsnxBCuoK9TCfJnNf.png]: actual ratio [1080/1920 = 0.56] does not match specified [348/581 = 0.59]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/sggQ3r5WMArudL5wg.png]: actual ratio [1080/1920 = 0.56] does not match specified [348/581 = 0.59]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/DDL3worcPrZTHRg3T.png]: actual ratio [1080/1920 = 0.56] does not match specified [348/581 = 0.59]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/pnL3YgdzTjxqmQNSo.png]: actual ratio [1080/1920 = 0.56] does not match specified [348/581 = 0.59]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/MdeLQYBGHWenog52u.png]: actual ratio [1080/1920 = 0.56] does not match specified [348/581 = 0.59]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/zsrwbmuN3kPpje542.png]: actual ratio [1080/1920 = 0.56] does not match specified [348/581 = 0.59]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/dv3nFsqCATX7rDt5T.png]: actual ratio [1080/1920 = 0.56] does not match specified [348/581 = 0.59]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/czNAcuZcXAsC6YxSA.png]: actual ratio [1080/1920 = 0.56] does not match specified [348/581 = 0.59]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/7vAkdatpwP8fCaQde.png]: actual ratio [1080/1920 = 0.56] does not match specified [348/581 = 0.59]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/5pAbTBa8HSHLZuvfz.png]: actual ratio [1080/1920 = 0.56] does not match specified [348/581 = 0.59]

ampvideoissmall (PASS)

ampvideoisspecifiedbyattribute (PASS)

bookendexists (WARN)

  <amp-story-bookend> not found

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

runtimeispreloaded (WARN)

  <link href=https://cdn.ampproject.org/v0.js rel=preload> is missing

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src] is missing

storymetadatathumbnailsareok (FAIL)

  [poster-landscape-src = {"url":"https://static.cleverpush.com/notification/icon/B3PtSjBTX7u4h2jjr.jpg","width":5794,"height":3894,"mime":"image/jpeg"}] failed [isLandscape]

storyruntimeisv1 (PASS)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
###################################################
https://stories.wmn.de/kon-mari-methode-aufraeumen
###################################################
ampimgamppixelpreferred (PASS)

ampimgheightwidthisok (PASS)

ampvideoissmall (PASS)

ampvideoisspecifiedbyattribute (PASS)

bookendexists (WARN)

  <amp-story-bookend> not found

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

runtimeispreloaded (WARN)

  <link href=https://cdn.ampproject.org/v0.js rel=preload> is missing

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"https://static.cleverpush.com/notification/icon/5FdjG2YaBtcAkZGPL.png","width":640,"height":853,"mime":"image/png"}] failed [isAtLeast696x928]

storymetadatathumbnailsareok (FAIL)

  [poster-square-src = {"url":"https://static.cleverpush.com/notification/icon/BRyCveobqLqn7FPTP.png","width":640,"height":853,"mime":"image/png"}] failed [isSquare, isAtLeast928x928]

storyruntimeisv1 (PASS)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
###################################################
https://www.rtl.de/cms/stories/das-grosse-interview-mit-harry-und-meghan/
###################################################
ampimgamppixelpreferred (PASS)

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/EJFj3Jmr9eKgioNrj.jpg]: actual ratio [647/1000 = 0.64] does not match specified [9/16 = 0.56]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/JSWbvdEpFmSPmsBbs.jpg]: actual ratio [219/24 = 9.12] does not match specified [87/9 = 9.66]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/WzqBfWi46jEMm3XAe.jpg]: actual ratio [591/1000 = 0.59] does not match specified [9/16 = 0.56]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/JSWbvdEpFmSPmsBbs.jpg]: actual ratio [219/24 = 9.12] does not match specified [87/9 = 9.66]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/JSWbvdEpFmSPmsBbs.jpg]: actual ratio [219/24 = 9.12] does not match specified [87/9 = 9.66]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/JSWbvdEpFmSPmsBbs.jpg]: actual ratio [219/24 = 9.12] does not match specified [87/9 = 9.66]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/JSWbvdEpFmSPmsBbs.jpg]: actual ratio [219/24 = 9.12] does not match specified [87/9 = 9.66]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/MyA9uP8icPiueqJWh.jpg]: actual ratio [667/1000 = 0.66] does not match specified [9/16 = 0.56]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/JSWbvdEpFmSPmsBbs.jpg]: actual ratio [219/24 = 9.12] does not match specified [87/9 = 9.66]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/6qHy3dgeCe8vxKNQi.jpg]: actual ratio [221/24 = 9.2] does not match specified [87/9 = 9.66]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/JSWbvdEpFmSPmsBbs.jpg]: actual ratio [219/24 = 9.12] does not match specified [87/9 = 9.66]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/MmadLP9HB4ShufnjE.jpg]: actual ratio [597/1000 = 0.59] does not match specified [9/16 = 0.56]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/JSWbvdEpFmSPmsBbs.jpg]: actual ratio [219/24 = 9.12] does not match specified [87/9 = 9.66]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/hzBoiehySY4wR9QjM.jpg]: actual ratio [1000/1000 = 1] does not match specified [9/16 = 0.56]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/JSWbvdEpFmSPmsBbs.jpg]: actual ratio [219/24 = 9.12] does not match specified [87/9 = 9.66]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/JSWbvdEpFmSPmsBbs.jpg]: actual ratio [219/24 = 9.12] does not match specified [87/9 = 9.66]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/9uTcQYsruS4jgKqix.jpg]: actual ratio [600/1000 = 0.6] does not match specified [9/16 = 0.56]

ampimgheightwidthisok (WARN)

  [https://static.cleverpush.com/notification/icon/JSWbvdEpFmSPmsBbs.jpg]: actual ratio [219/24 = 9.12] does not match specified [87/9 = 9.66]

ampvideoissmall (FAIL)

  videos over 4MB: [https://static.cleverpush.com/notification/icon/jyj4XhAZYEB83uZgw.mp4,https://static.cleverpush.com/notification/icon/ywyey2oAnS8shaLPW.mp4,https://static.cleverpush.com/notification/icon/wCpnFx6Hs5eHyiGt8.mp4]

ampvideoisspecifiedbyattribute (PASS)

bookendexists (WARN)

  <amp-story-bookend> not found

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

runtimeispreloaded (WARN)

  <link href=https://cdn.ampproject.org/v0.js rel=preload> is missing

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (FAIL)

  [publisher-logo-src = {"url":"https://static.cleverpush.com/notification/icon/u7hroQ2tpeH4GPFxm.png","width":600,"height":60,"mime":"image/png"}] failed [isSquare, isAtLeast96x96]

storymetadatathumbnailsareok (FAIL)

  [poster-square-src = {"url":"https://static.cleverpush.com/notification/icon/9CqkJ88tjFN9NCR42.png","width":720,"height":720,"mime":"image/png"}] failed [isAtLeast928x928]

storyruntimeisv1 (PASS)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by manavpeerbits** [comment]
Hello @Dbrown910 
Thanks for your review.

We've followed above mentioned AMP validation guideline and fixed all the FAIL cases but having issue to resolve the WARN cases.

e.g.
runtimeispreloaded : Do we need to preload imported scripts in AMP HTML ?
like below 
<link rel="preload" href="style.css" as="style">
<link rel="preload" href="main.js" as="script">

and also how can I check that this WARNINGS are resolved or not.
because #development=1 is not showing below warnings.

WARN Cases 
runtimeispreloaded : is missing
 bookendexists : not found
  ampimgheightwidthisok : actual ratio [1080/1920 = 0.56] does not match specified [348/581 = 0.59]
  
  
  Thanks in advance.

**Comment by Dbrown910** [comment]
Hi @manavpeerbits 

These particular warnings are just for best practices. I'd recommend preloading the runtime, and optimizing the images as these can help the content load faster. In general though, what you see in the #development=1 console is sufficient enough to pass, so I won't include the warnings in the future reviews.

I am still seeing issues with the poster and logo images though. Have the changes been pushed to the URLs above?

###################################################
https://stories.bildderfrau.de/die-koestlichsten-fruehstucksrezepte
###################################################
ampimgamppixelpreferred (PASS)

ampimgheightwidthisok (PASS)

ampvideoissmall (PASS)

ampvideoisspecifiedbyattribute (PASS)

bookendexists (WARN)

  <amp-story-bookend> not found

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"https://static.cleverpush.com/notification/icon/XQaMnrQuSgKsrBLwn.png","width":640,"height":853,"mime":"image/png"}] failed [isAtLeast696x928]

storymetadatathumbnailsareok (FAIL)

  [poster-square-src = {"url":"https://static.cleverpush.com/notification/icon/i7rq6YJdwy74BMjCh.png","width":640,"height":853,"mime":"image/png"}] failed [isSquare, isAtLeast928x928]

storyruntimeisv1 (PASS)

###################################################
https://stories.bildderfrau.de/dessert-rezepte-weihnachten
###################################################
ampimgamppixelpreferred (PASS)

ampimgheightwidthisok (PASS)

ampvideoissmall (PASS)

ampvideoisspecifiedbyattribute (PASS)

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (PASS)

storyruntimeisv1 (PASS)

###################################################
https://stories.giga.de/ps5
###################################################
ampimgamppixelpreferred (PASS)

ampvideoissmall (PASS)

ampvideoisspecifiedbyattribute (PASS)

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (PASS)

storyruntimeisv1 (PASS)

###################################################
https://stories.giga.de/prime-day
###################################################
ampimgamppixelpreferred (PASS)

ampvideoissmall (PASS)

ampvideoisspecifiedbyattribute (PASS)

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"https://static.cleverpush.com/notification/icon/uc57ES53EWq3fkuhb.png","width":300,"height":400,"mime":"image/png"}] failed [isAtLeast696x928]

storyruntimeisv1 (PASS)

###################################################
https://stories.futurezone.de/krebserregende-lebensmittel
###################################################
ampimgamppixelpreferred (PASS)

ampimgheightwidthisok (PASS)

ampvideoissmall (PASS)

ampvideoisspecifiedbyattribute (PASS)

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"https://static.cleverpush.com/notification/icon/cg5BWDw7ScJghTWMB.png","width":650,"height":853,"mime":"image/png"}] failed [isPortrait, isAtLeast696x928]

storyruntimeisv1 (PASS)

###################################################
https://stories.futurezone.de/signal-app
###################################################
ampimgamppixelpreferred (PASS)

ampimgheightwidthisok (PASS)

ampvideoissmall (PASS)

ampvideoisspecifiedbyattribute (PASS)

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"https://static.cleverpush.com/notification/icon/bpv9PCM3eEoyKaYTB.png","width":650,"height":853,"mime":"image/png"}] failed [isPortrait, isAtLeast696x928]

storyruntimeisv1 (PASS)

###################################################
https://stories.desired.de/stars
###################################################
ampimgamppixelpreferred (PASS)

ampimgheightwidthisok (PASS)

ampvideoissmall (PASS)

ampvideoisspecifiedbyattribute (PASS)

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (PASS)

storyruntimeisv1 (PASS)

###################################################
https://stories.waz.de/ffp2masken
###################################################
ampimgamppixelpreferred (PASS)

ampvideoissmall (PASS)

ampvideoisspecifiedbyattribute (PASS)

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src] is missing

storymetadatathumbnailsareok (FAIL)

  [poster-landscape-src = {"url":"https://static.cleverpush.com/notification/icon/B3PtSjBTX7u4h2jjr.jpg","width":5794,"height":3894,"mime":"image/jpeg"}] failed [isLandscape]

storyruntimeisv1 (PASS)

###################################################
https://stories.wmn.de/kon-mari-methode-aufraeumen
###################################################
ampimgamppixelpreferred (PASS)

ampimgheightwidthisok (PASS)

ampvideoissmall (PASS)

ampvideoisspecifiedbyattribute (PASS)

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"https://static.cleverpush.com/notification/icon/5FdjG2YaBtcAkZGPL.png","width":640,"height":853,"mime":"image/png"}] failed [isAtLeast696x928]

storymetadatathumbnailsareok (FAIL)

  [poster-square-src = {"url":"https://static.cleverpush.com/notification/icon/BRyCveobqLqn7FPTP.png","width":640,"height":853,"mime":"image/png"}] failed [isSquare, isAtLeast928x928]

storyruntimeisv1 (PASS)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
###################################################
https://www.rtl.de/cms/stories/das-grosse-interview-mit-harry-und-meghan/
###################################################
ampimgamppixelpreferred (PASS)

ampvideoissmall (FAIL)

  videos over 4MB: [https://static.cleverpush.com/notification/icon/jyj4XhAZYEB83uZgw.mp4,https://static.cleverpush.com/notification/icon/ywyey2oAnS8shaLPW.mp4,https://static.cleverpush.com/notification/icon/wCpnFx6Hs5eHyiGt8.mp4]

ampvideoisspecifiedbyattribute (PASS)

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (FAIL)

  [publisher-logo-src = {"url":"https://static.cleverpush.com/notification/icon/u7hroQ2tpeH4GPFxm.png","width":600,"height":60,"mime":"image/png"}] failed [isSquare, isAtLeast96x96]

storymetadatathumbnailsareok (FAIL)

  [poster-square-src = {"url":"https://static.cleverpush.com/notification/icon/9CqkJ88tjFN9NCR42.png","width":720,"height":720,"mime":"image/png"}] failed [isAtLeast928x928]

storyruntimeisv1 (PASS)

**Comment by gbhrdt** [comment]
Hi @Dbrown910 - all FAIL errors should be fixed now! Thanks for checking again 👍

**Comment by Dbrown910** [comment]
Hi @gbhrdt. Sorry for the delay. Everything looks good except on the last story, the poster square is still too small. 
(928x928 min). I'm working on a PR for the tool listing so as soon as this gets cleared I can open it.

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
###################################################
https://www.rtl.de/cms/stories/das-grosse-interview-mit-harry-und-meghan/
###################################################
ampimgamppixelpreferred (PASS)

ampvideoissmall (PASS)

ampvideoisspecifiedbyattribute (PASS)

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (FAIL)

  [poster-square-src = {"url":"https://static.cleverpush.com/notification/icon/9CqkJ88tjFN9NCR42.png","width":720,"height":720,"mime":"image/png"}] failed [isAtLeast928x928]

storyruntimeisv1 (PASS)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by gbhrdt** [comment]
Hi @Dbrown910 no problem - the poster square image for the mentioned story should be correct now.

**Comment by Dbrown910** [comment]
@gbhrdt PR is up
